### ISSUE TITLE
18.4.26bug报告,hosts打不开谷歌搜索。问题已经重新编辑描述的很详细

### ISSUE THREAD

**Issue by yun2673436976** [googlehosts/hosts#204] opened 2018-04-26 03:37 UTC
我从https://coding.net/u/scaffrey/p/hosts/git/tree/master?public=true  下载压缩包，解压，用记事本打开scaffrey的hosts，把scaffrey的hosts里面的全部内容复制，再用dism++打开本地硬盘的hosts，把scaffrey的hosts里面的内容全部复制到本地硬盘hosts。用dnsjump刷新dns，然后用火狐打开https://www.google.co.jp/?gws_rd=ssl     https://www.google.com/ncr  都不能打开谷歌。我是广东电信。这是我使用的hosts代码(github限制我不能把所有代码粘贴出来)：
# Copyright (c) 2017-2018, googlehosts members.
# https://github.com/googlehosts/hosts
# Last updated: 2018-04-25

# This work is licensed under a modified HOSTS License.
# https://github.com/googlehosts/hosts/raw/master/LICENSE

# Modified Hosts Start

# Localhost (DO NOT REMOVE) Start
127.0.0.1	localhost
::1	localhost
::1	ip6-localhost
::1	ip6-loopback
# Localhost (DO NOT REMOVE) End

# Akamai Start
23.32.241.9	a248.e.akamai.net
23.32.241.16	static.ak.instagram.com
184.51.15.69	images.ak.instagram.com
104.77.23.93	passets-cdn.pinterest.com
104.71.149.138	s.pinimg.com
104.71.149.138	i.pinimg.com
104.71.149.138	v.pinimg.com
104.71.149.138	s-media-cache-ak0.pinimg.com
23.51.209.100	blogthumb.pstatic.net
# Akamai End

# Amazon AWS Start
52.219.0.4	s3-ap-northeast-1.amazonaws.com

54.231.249.17	s3-ap-southeast-2.amazonaws.com
# Amazon AWS End

**Comment by Ir1d** [comment] 2018-04-26 03:39
具体点？

**Comment by beyondgfw** [comment] 2018-04-26 03:44
@yun2673436976 未发现镜像有同步问题。
如果只是某个网站不能用的话，请更改您的 issue 标题和说明。

**Comment by yun2673436976** [comment] 2018-04-26 03:55
我从https://coding.net/u/scaffrey/p/hosts/git/tree/master?public=true  下载压缩包，解压，用记事本打开scaffrey的hosts，把scaffrey的hosts里面的全部内容复制，再用dism++打开本地硬盘的hosts，把scaffrey的hosts里面的内容全部复制到本地硬盘hosts。用dnsjump刷新dns，然后用火狐打开https://www.google.co.jp/?gws_rd=ssl     https://www.google.com/ncr  都不能打开谷歌。我是广东电信。这是我使用的hosts代码(github限制我不能把所有代码粘贴出来)：
# Copyright (c) 2017-2018, googlehosts members.
# https://github.com/googlehosts/hosts
# Last updated: 2018-04-25

# This work is licensed under a modified HOSTS License.
# https://github.com/googlehosts/hosts/raw/master/LICENSE

# Modified Hosts Start

# Localhost (DO NOT REMOVE) Start
127.0.0.1	localhost
::1	localhost
::1	ip6-localhost
::1	ip6-loopback
# Localhost (DO NOT REMOVE) End

# Akamai Start
23.32.241.9	a248.e.akamai.net
23.32.241.16	static.ak.instagram.com
184.51.15.69	images.ak.instagram.com
104.77.23.93	passets-cdn.pinterest.com
104.71.149.138	s.pinimg.com
104.71.149.138	i.pinimg.com
104.71.149.138	v.pinimg.com
104.71.149.138	s-media-cache-ak0.pinimg.com
23.51.209.100	blogthumb.pstatic.net
# Akamai End

# Amazon AWS Start
52.219.0.4	s3-ap-northeast-1.amazonaws.com
54.231.249.17	s3-ap-southeast-2.amazonaws.com
# Amazon AWS End

# Android Start
108.177.120.94	a.android.com
108.177.120.94	b.android.com
108.177.120.94	m.android.com
108.177.120.94	connectivitycheck.android.com
108.177.120.94	d.android.com
108.177.120.94	dev.android.com
108.177.120.94	market.android.com
108.177.120.94	r.android.com
216.58.217.196	android.com
172.217.4.174	www.android.com
172.217.4.174	source.android.com
172.217.4.174	developer.android.com
# Android End

# Androidfilehost Start
151.139.240.14	androidfilehost.com
# Androidfilehost End

# Apkpure Start
104.20.82.194	apkpure.com
104.20.82.194	a.apkpure.com
104.20.82.194	download.apkpure.com
104.20.82.194	m.apkpure.com
104.20.82.194	i.apkpure.com
104.20.82.194	static.apkpure.com
104.20.82.194	translate.apkpure.com
# Apkpure End

# Apkmirror Start
104.19.133.58	www.apkmirror.com
# Apkmirror End

# Appspot Start
64.233.188.151	www.appspot.com
64.233.188.151	appspot.com
64.233.188.151	events.withgoogle.com
64.233.188.151	summerofcode.withgoogle.com
64.233.188.151	foobar.withgoogle.com
64.233.188.151	interstellar.withgoogle.com
64.233.188.151	edudirectory.withgoogle.com
64.233.188.151	atmosphere.withgoogle.com
64.233.188.151	accelerate.withgoogle.com
64.233.188.151	insgruene.withgoogle.com
64.233.188.151	atmospheretokyo.withgoogle.com
64.233.188.151	connectedclassrooms.withgoogle.com
64.233.188.151	smartypins.withgoogle.com
64.233.188.151	streetart.withgoogle.com
64.233.188.151	cardboard.withgoogle.com
64.233.188.151	kickwithchrome.withgoogle.com
64.233.188.151	candidatos.withgoogle.com
64.233.188.151	trendstw.withgoogle.com
64.233.188.151	impactchallenge.withgoogle.com
64.233.188.151	eduproducts.withgoogle.com
64.233.188.151	onetoday.google.com
64.233.188.151	withgoogle.com
64.233.188.151	www.withgoogle.com
64.233.188.151	cloudnext.withgoogle.com
64.233.188.151	edutrainingcenter.withgoogle.com
64.233.188.151	earthview.withgoogle.com
64.233.188.151	lightsaber.withgoogle.com
64.233.188.151	britishmuseum.withgoogle.com
64.233.188.151	beyondthemap.withgoogle.com
64.233.188.151	analyticsacademy.withgoogle.com
64.233.188.151	spellup.withgoogle.com
# Appspot End

# Appspotpreview Start
172.217.161.180	author-dot-betaspike.appspot.com
172.217.161.180	jmoore-dot-android-experiments.appspot.com
172.217.161.180	mission-author-dot-betaspike.appspot.com
172.217.161.180	drivenotepad.appspot.com
172.217.161.180	virustotalcloud.appspot.com
172.217.161.180	joinjoaomgcd.appspot.com
172.217.161.180	m-dot-betaspike.appspot.com
172.217.161.180	download-chromium.appspot.com
172.217.161.180	google-developers.appspot.com
172.217.161.180	chrometophone.appspot.com
172.217.161.180	chrome-devtools-frontend.appspot.com
172.217.161.180	apis-explorer.appspot.com
172.217.161.180	betaspike.appspot.com
172.217.161.180	hstspreload.appspot.com
172.217.161.180	lfe-alpo-gm.appspot.com
# Appspotpreview End

# Archive Start
207.241.225.95	archive.org
207.241.225.95	www.archive.org
207.241.225.95	analytics.archive.org
207.241.225.95	ia802704.us.archive.org
207.241.224.19	web-beta.archive.org
207.241.224.19	wwwb-sentry.us.archive.org
207.241.224.19	web.archive.org
207.241.224.6	mail.archive.org
207.241.224.21	books-general.archive.org
# Archive End

# Armorgames Start
192.229.173.251	agi.armorgames.com
192.229.173.251	armatars.armorgames.com
192.229.173.251	cache.armorgames.com
192.229.173.251	gamemedia.armorgames.com
192.229.173.251	quests.armorgames.com
# Armorgames End

# Arukas Start
27.133.136.8	app.arukas.io
# Arukas End

# Bandwagonhost Start
104.20.6.63	bandwagonhost.com
# Bandwagonhost End

# Box Start
107.152.25.196	box.com
107.152.24.198	app.box.com
107.152.24.197	account.box.com
107.152.24.197	upload.box.com
107.152.24.197	m.box.com
# Box End

# Change.org Start
104.16.5.13	www.change.org
104.16.5.13	assets.change.org
104.16.4.13	change.org
104.16.4.13	assets-fe.change.org
# Change.org End

# Cloudfront Start
52.84.167.78	d3c33hcgiwev3.cloudfront.net
52.84.167.78	d3njjcbhbojbot.cloudfront.net
# Cloudfront End

# Culturalspot Start
172.217.31.96	embed.culturalspot.org
# Culturalspot End

# Conoha Start
157.7.225.122	cp.conoha.jp
103.3.190.48	www.conoha.jp
157.7.225.117	app.conoha.jp
157.7.225.120	manage.conoha.jp
# Conoha End

# Dropbox Start
162.125.248.2	db.tt
162.125.248.1	www.dropbox.com
162.125.248.1	www.dualstack.dropbox-dns.com
162.125.248.1	api.dropbox.com
162.125.248.1	api.dualstack.dropbox-dns.com
162.125.248.1	api.dropboxapi.com
162.125.32.135	api-d.dropbox.com
162.125.32.13	api.v.dropbox.com
162.125.32.13	api-notify.dropbox.com
54.230.86.72	aem.dropbox.com
162.125.82.8	api-content.dropbox.com
162.125.82.5	api-content-photos.dropbox.com
52.222.238.253	blogs.dropbox.com
162.125.32.2	block.dropbox.com
162.125.17.5	block.v.dropbox.com
162.125.18.133	bolt.dropbox.com
162.125.2.3	client.dropbox.com
162.125.2.3	client-cf.dropbox.com
162.125.32.12	client.v.dropbox.com
162.125.80.3	client-lb.dropbox.com
162.125.80.3	client-web.dropbox.com
162.125.32.5	d.dropbox.com
162.125.32.5	d.v.dropbox.com
162.125.2.6	dl.dropbox.com
162.125.2.6	dl-web.dropbox.com
162.125.80.6	dl-doc.dropbox.com
34.197.94.108	dl-debug.dropbox.com
52.85.12.7	forums.dropbox.com
54.192.136.115	linux.dropbox.com
162.125.32.9	m.dropbox.com
52.85.12.227	marketing.dropbox.com
162.125.17.131	notify.dropbox.com
162.125.32.15	photos.dropbox.com
162.125.80.5	photos-1.dropbox.com
162.125.80.5	photos-2.dropbox.com
162.125.80.5	photos-3.dropbox.com
162.125.80.5	photos-4.dropbox.com
162.125.80.5	photos-5.dropbox.com
162.125.80.5	photos-6.dropbox.com
162.125.80.5	photos-thumb.dropbox.com
162.125.18.129	photos-thumb.x.dropbox.com
162.125.2.3	paper.dropbox.com
52.222.238.128	status.dropbox.com
52.85.12.72	snapengage.dropbox.com
162.125.2.6	dl.dropboxusercontent.com
162.125.32.10	www.dropboxstatic.com
104.16.100.29	cfl.dropboxstatic.com
54.230.125.126	cf.dropboxstatic.com
162.125.32.10	dbxlocal.dropboxstatic.com
162.125.82.2	log.getdropbox.com
# Dropbox End

# DuckDuckGo Start
13.210.167.213	duckduckgo.com
13.210.167.213	www.duckduckgo.com
13.210.167.213	ac.duckduckgo.com
13.210.167.213	start.duckduckgo.com
13.210.167.213	help.duckduckgo.com
13.210.184.136	icons.duckduckgo.com
13.210.184.136	proxy.duckduckgo.com
13.210.184.136	images.duckduckgo.com
# DuckDuckGo End

# Disqus Start
151.101.0.134	disqus.com
151.101.24.134	www.disqus.com
151.101.24.134	dropbox.disqus.com
151.101.24.134	nytchinese.disqus.com
151.101.24.64	glitter.services.disqus.com
151.101.52.64	links.services.disqus.com
173.192.82.196	realtime.services.disqus.com
50.18.252.168	help.disqus.com
151.101.52.134	content.disqus.com
151.101.52.134	referrer.disqus.com
151.101.40.134	docs.disqus.com
151.101.40.134	apkpure.disqus.com
96.7.54.196	about.disqus.com
96.7.54.200	blog.disqus.com
96.7.54.198	publishers.disqus.com
104.16.80.166	c.disquscdn.com
151.101.26.49	a.disquscdn.com
# Disqus End

# Facebook Start
157.240.7.35	www.facebook.com
157.240.7.35	fb.me
157.240.7.35	facebook.com
157.240.7.35	api.facebook.com
157.240.7.35	apps.facebook.com
157.240.7.35	attachments.facebook.com
157.240.7.35	business.facebook.com
157.240.7.35	bigzipfiles.facebook.com
157.240.7.35	code.facebook.com
157.240.7.35	check4.facebook.com
157.240.7.35	check6.facebook.com
157.240.7.35	connect.facebook.com
157.240.7.35	d.facebook.com
157.240.7.35	developers.facebook.com
157.240.7.35	graph.facebook.com
157.240.7.35	l.facebook.com
157.240.7.35	login.facebook.com
157.240.7.35	m.facebook.com
157.240.7.35	mtouch.facebook.com
157.240.7.35	mqtt.facebook.com
157.240.7.35	mqtt-mini.facebook.com
157.240.7.35	orcart.facebook.com
157.240.7.35	pixel.facebook.com
157.240.7.35	scontent.facebook.com
157.240.7.35	ssl.facebook.com
157.240.7.35	star.facebook.com
157.240.7.35	secure.facebook.com
157.240.7.35	staticxx.facebook.com
157.240.7.35	touch.facebook.com
157.240.7.35	upload.facebook.com
157.240.7.35	vupload.facebook.com
157.240.7.35	vupload2.facebook.com
157.240.7.35	api-read.facebook.com
157.240.7.35	b-api.facebook.com
157.240.7.35	b-graph.facebook.com
157.240.7.35	s-static.facebook.com
157.240.7.35	zh-cn.facebook.com
157.240.7.35	zh-tw.facebook.com
157.240.7.35	edge-chat.facebook.com
157.240.7.35	0-edge-chat.facebook.com
157.240.7.35	1-edge-chat.facebook.com
157.240.7.35	2-edge-chat.facebook.com
157.240.7.35	3-edge-chat.facebook.com
157.240.7.35	4-edge-chat.facebook.com
157.240.7.35	5-edge-chat.facebook.com
157.240.7.35	6-edge-chat.facebook.com
157.240.7.35	channel-ecmp-05-ash3.facebook.com
157.240.7.35	channel-staging-ecmp-05-ash3.facebook.com
157.240.7.35	channel-testing-ecmp-05-ash3.facebook.com
157.240.7.35	beta-chat-01-05-ash3.facebook.com
157.240.7.35	s-static.ak.facebook.com
157.240.7.35	star.c10r.facebook.com
157.240.7.35	fbcdn.net
157.240.7.35	connect.facebook.net
157.240.7.35	ent-a.xx.fbcdn.net
157.240.7.35	ent-b.xx.fbcdn.net
157.240.7.35	ent-c.xx.fbcdn.net
157.240.7.35	ent-d.xx.fbcdn.net
157.240.7.35	ent-e.xx.fbcdn.net
157.240.7.35	scontent.xx.fbcdn.net
157.240.7.35	scontent-a.xx.fbcdn.net
157.240.7.35	scontent-b.xx.fbcdn.net
157.240.7.35	scontent-c.xx.fbcdn.net
157.240.7.35	scontent-d.xx.fbcdn.net
157.240.7.35	scontent-e.xx.fbcdn.net
157.240.7.35	scontent-mxp.xx.fbcdn.net
157.240.7.35	scontent-a-lax.xx.fbcdn.net
157.240.7.35	scontent-a-sin.xx.fbcdn.net
157.240.7.35	scontent-b-lax.xx.fbcdn.net
157.240.7.35	scontent-b-sin.xx.fbcdn.net
157.240.7.35	static.thefacebook.com
157.240.7.35	attachment.fbsbx.com
157.240.7.35	messenger.com
157.240.7.35	www.messenger.com
157.240.7.35	0-edge-chat.messenger.com
157.240.7.35	1-edge-chat.messenger.com
157.240.7.35	2-edge-chat.messenger.com
157.240.7.35	3-edge-chat.messenger.com
157.240.7.35	4-edge-chat.messenger.com
157.240.7.35	5-edge-chat.messenger.com
157.240.7.35	6-edge-chat.messenger.com
31.13.95.33	snaptu-z.facebook.com
31.13.95.33	snaptu-p1.facebook.com
31.13.95.33	snaptu-p2.facebook.com
31.13.95.5	edge-mqtt.facebook.com
192.0.78.13	instantarticles.fb.com
192.0.78.13	live.fb.com
192.0.78.13	managingbias.fb.com
192.0.78.13	nonprofits.fb.com
192.0.78.13	rightsmanager.fb.com
192.0.78.13	techprep.fb.com
192.0.78.13	work.fb.com
31.13.91.15	static.xx.fbcdn.net
31.13.91.15	scontent-lax3-1.xx.fbcdn.net
31.13.91.15	scontent-lax3-2.xx.fbcdn.net
31.13.91.15	scontent-lax3-3.xx.fbcdn.net
31.13.91.15	scontent-lax3-4.xx.fbcdn.net
31.13.91.15	scontent-hkg3-1.xx.fbcdn.net
31.13.91.15	scontent-hkg3-2.xx.fbcdn.net
31.13.91.15	scontent-hkg3-3.xx.fbcdn.net
31.13.91.15	z-1-scontent.xx.fbcdn.net
31.13.91.15	video-lax3-1.xx.fbcdn.net
31.13.91.15	video-lax3-2.xx.fbcdn.net
31.13.91.15	video-lax3-3.xx.fbcdn.net
31.13.91.15	video-lax3-4.xx.fbcdn.net
31.13.91.15	video-mrs1-1.xx.fbcdn.net
31.13.91.15	video-mrs1-2.xx.fbcdn.net
31.13.91.15	video-mrs1-3.xx.fbcdn.net
31.13.91.15	video-mrs1-4.xx.fbcdn.net
31.13.91.15	video-hkg3-1.xx.fbcdn.net
31.13.91.15	video-sit4-1.xx.fbcdn.net
31.13.91.15	external.xx.fbcdn.net
192.0.66.2	messengerplatform.fb.com
192.0.66.2	threatexchange.fb.com
157.240.11.18	video.xx.fbcdn.net
# Facebook End

# FlipBoard Start
52.44.186.59	beacon.flipboard.com
34.201.185.200	fbprod.flipboard.com
# FlipBoard End

# Github Start
192.30.253.118	gist.github.com
192.30.253.112	github.com
192.30.253.112	www.github.com
# Github End

# Gmail Start
108.177.122.160	gmail.com
108.177.111.161	www.gmail.com
108.177.111.161	googlemail.l.google.com
74.125.70.162	mail-settings.google.com
74.125.26.161	m.gmail.com
74.125.132.160	m.googlemail.com
108.177.122.161	gmail.google.com
172.217.168.197	mail.google.com
172.217.14.118	inbox.google.com
172.217.15.22	chatenabled.mail.google.com
74.125.202.162

**Comment by yun2673436976** [comment] 2018-04-26 04:14
@beyondgfw @Ir1d 问题已经描述完，请你在本楼中看。在此谢谢各位的帮助，还要提供什么吗？

**Comment by beyondgfw** [comment] 2018-04-26 04:37
@yun2673436976 不需要把 hosts 内容贴出来，只需要告知 hosts 文件的日期即可（见开头部分）。
关于谷歌相关的问题，请参阅 [wiki](https://github.com/googlehosts/hosts/wiki)。

**Comment by beyondgfw** [comment] 2018-04-26 04:37
@yun2673436976 Duplicate of #64

**Comment by SerCom-KC** [comment] 2018-04-26 04:38
Duplicate of #64

**Closed by SerCom-KC** 2018-04-26 04:38 UTC

**Comment by yun2673436976** [comment] 2018-04-26 05:00
@beyondgfw 我是github新手，看了wiki才知道GFW 利用了现有协议中的漏洞对这些网站进行针对性封杀，所以用hosts依旧上不了谷歌，以后我要反馈问题，先看项目wiki。如果谷歌都上不了，请问你持续更新的hosts有什么用？谢谢你的答复。

**Comment by SerCom-KC** [comment] 2018-04-26 05:10
全世界又不只谷歌一个网站被封……
维基百科还禁止挂代理编辑呢（
