### ISSUE TITLE
173.194.198.82 gcr.io cant't work

### ISSUE THREAD

**Issue by fanhaozzu** [googlehosts/hosts#154] opened 2017-12-25 06:55 UTC
173.194.198.82 gcr.io cant't work

**Comment by fanhaozzu** [comment] 2017-12-25 06:55
173.194.198.82 gcr.io cant't work

**Comment by SerCom-KC** [comment] 2017-12-25 07:03
Most Google services are not available via hosts at the moment.
Closing this issue as a duplicate of #64.

**Comment by SerCom-KC** [comment] 2017-12-25 07:04
Most Google services are not available via hosts at the moment.
Closing this issue as a duplicate of #64.

**Comment by SerCom-KC** [comment] 2017-12-25 07:14
Re-opening since this domain is not in the blacklist.
cc @lrinQVQ

**Comment by lrinQVQ** [comment] 2017-12-25 07:21
Get I will try to fix it

**Comment by Runrioter** [comment] 2018-02-08 01:40
Will this is fixed ?

**Comment by lrinQVQ** [comment] 2018-02-08 02:50
This domain needs Google Code ip.
It takes a lot of time to find it

**Comment by limjoe** [comment] 2018-02-27 08:11
什么时候修复？之前网上公开的 gcr.io 都不能用了

**Comment by SerCom-KC** [comment] 2018-02-27 09:22
@limjoe 
正如 @lrinQVQ 所说，`gcr.io` 只能用 Google Code 的 IP，普通的 gws IP 是用不了的，所以很难找

**Comment by fanhaozzu** [comment] 2018-03-07 05:13
https://github.com/fanhaozzu/googlehost，大家可以试试

**Comment by SerCom-KC** [comment] 2018-03-07 05:19
姑且提醒一下各位，楼上使用的是非官方（腾讯）IP

**Comment by beyondgfw** [comment] 2018-08-28 06:27
跟 #64 合并处理。

**Closed by beyondgfw** 2018-08-28 06:27 UTC
Labels: bug
