### ISSUE TITLE
楼主，改了hosts以后依然ping不通google哦。。。

### ISSUE THREAD

**Issue by xingege662** [googlehosts/hosts#96] opened 2017-10-12 07:32 UTC
PING www.google.com (172.217.60.241): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2

**Comment by beyondgfw** [comment] 2017-10-12 09:19
Duplicate of #64

**Closed by beyondgfw** 2017-10-12 09:19 UTC
