### ISSUE TITLE
Wikinews & Wikipedia not working

### ISSUE THREAD

**Issue by xinlingcheng** [googlehosts/hosts#271] opened 2018-10-26 02:11 UTC
### 是什么网站 / app 出现了问题？

- [ ] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [ ] 完全无法使用：

- [ ] 部分无法使用：

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方

# 请将 hosts 内容粘贴在此行上方
```

**Comment by xinlingcheng** [comment] 2018-10-26 02:14
this ip(198.35.26.96 ) doesn't work, and this ip(208.80.153.224) works

**Comment by xinlingcheng** [comment] 2018-10-26 02:28
> Please indicate the problematic domain(s) in the issue title or the body (we can't simply identify it by IP, cases where one IP were used in multiple domains exists), or I'll mark this issue as invalid and close it.

all the wikipedia sites
# Wikinews Start
198.35.26.96	zh.wikinews.org
198.35.26.96	zh.m.wikinews.org
# Wikinews End

# Wikipedia Start
198.35.26.96	www.wikipedia.org
198.35.26.96	login.wikimedia.org
198.35.26.96	wuu.wikipedia.org
198.35.26.96	zh-yue.wikipedia.org
198.35.26.96	zh.wikipedia.org
198.35.26.96	zh.m.wikipedia.org
198.35.26.96	ja.wikipedia.org
198.35.26.96	ja.m.wikipedia.org
198.35.26.96	ug.wikipedia.org
198.35.26.96	ug.m.wikipedia.org
198.35.26.112	upload.wikimedia.org
# Wikipedia End

**Comment by SerCom-KC** [comment] 2018-10-26 02:46
> all the wikipedia sites

Thank you.
Be sure to follow our issue template next time. I'll change the issue title for you.

**Comment by xinlingcheng** [comment] 2018-10-26 02:53
> > all the wikipedia sites
> 
> Thank you.
> Be sure to follow our issue template next time. I'll change the issue title for you.

OK , many thanks！

**Comment by lrinQVQ** [comment] 2018-10-26 05:13
*.wikipedia.org not polluted by DNS, nor blocked IP,Just SNI RST

**Comment by SerCom-KC** [comment] 2018-10-26 05:18
Oops, forgot this thing.
Duplicate of #248.

**Closed by SerCom-KC** 2018-10-26 05:18 UTC
