### ISSUE TITLE
添加hosts后还是无法访问Google

### ISSUE THREAD

**Issue by kervin521** [googlehosts/hosts#165] opened 2018-01-24 02:08 UTC
@SerCom-KC @beyondgfw 

![image](https://user-images.githubusercontent.com/9798724/35310870-81f1c372-00ee-11e8-8ad5-636c8b45c8e9.png)

**Comment by SerCom-KC** [comment] 2018-01-24 03:53
Duplicate of #64

**Closed by SerCom-KC** 2018-01-24 03:53 UTC

**Comment by SerCom-KC** [comment] 2018-01-24 12:27
而且请小心，因为路由跟踪会暴露 IP，个人建议移除图片

**Comment by lrinQVQ** [comment] 2018-04-09 00:13
fix now
https://github.com/googlehosts/hosts/commit/e56456b8027b3046770cf6d64cdf404cabe968ac
