### ISSUE TITLE
I could't open the google website with https://google.com. 

### ISSUE THREAD

**Issue by SeanBurt** [googlehosts/hosts#163] opened 2018-01-23 03:50 UTC
Mac OS X High Sierra Version 10.13.2
Hosts last updated: 2018-01-23.
But i could't open the google website with https://google.com. 
So, how can i do?
Thx!

**Comment by SerCom-KC** [comment] 2018-01-23 03:58
See [wiki](https://github.com/googlehosts/hosts/wiki/FAQ-(English)#why-are-we-still-unable-to-use-googletwitterfacebookonedrivedropbox) for explanation.
Duplicate of #64

**Closed by SerCom-KC** 2018-01-23 03:58 UTC
