### ISSUE TITLE
MEGA ip has changed

### ISSUE THREAD

**Issue by functionxxx** [googlehosts/hosts#285] opened 2018-12-17 03:50 UTC
### 是什么网站 / app 出现了问题？

- [X] 我确认这不是一个 NSFW 网站

### 是完全无法使用，还是部分无法使用？
- [X] 完全无法使用：

- [ ] 部分无法使用：

### 您的运营商是？
联通

### 加载失败的资源地址
mega.nz

### 封锁方式
- [ ] DNS 污染
- [ ] IP 封锁
- [ ] TCP Reset
- [ ] 涉及到第三方服务：

### 可用的 hosts
```
# 请将 hosts 内容粘贴在此行下方
89.44.169.135	mega.nz
# 请将 hosts 内容粘贴在此行上方
```

**Comment by SerCom-KC** [comment] 2018-12-17 03:51
Possible duplicate of #284

**Comment by functionxxx** [comment] 2018-12-17 05:42
Both I've tested, but it seems that 89.44.169.135 has less hops and packet loss on my network.

**Comment by functionxxx** [comment] 2018-12-18 05:51
Tracing route to 89.44.169.135 over a maximum of 30 hops:

  8   183 ms   183 ms   183 ms  63.243.205.89
  9   333 ms   333 ms   333 ms  63.243.128.28
 10   333 ms   333 ms   333 ms  63.243.128.26
 11   333 ms   333 ms   333 ms  216.6.90.22
 12   333 ms   333 ms   333 ms  80.231.130.105
 13   333 ms   333 ms   333 ms  80.231.154.142
 14   316 ms   316 ms   316 ms  80.231.153.49
 15   333 ms   316 ms   316 ms  80.231.153.23
 16   333 ms   333 ms   333 ms  5.23.10.10
 17   333 ms   333 ms   333 ms  89.44.169.135

Trace complete.


Tracing route to 31.216.148.10 over a maximum of 30 hops:

  8     *      233 ms   233 ms  38.88.197.41
  9   233 ms     *        *     154.54.25.149
 10   250 ms   250 ms   250 ms  154.54.45.161
 11   250 ms     *      250 ms  154.54.42.78
 12     *        *      266 ms  154.54.29.221
 13     *      283 ms   283 ms  154.54.28.69
 14   300 ms     *      300 ms  154.54.7.157
 15     *        *      300 ms  154.54.40.105
 16     *      366 ms     *     66.28.4.198
 17   383 ms     *      383 ms  154.54.78.94
 18   383 ms   383 ms   383 ms  154.25.12.70
 19   366 ms   400 ms   416 ms  149.6.66.198
 20   366 ms   383 ms   416 ms  31.216.148.10

Trace complete.


Pinging 89.44.169.135 with 64 bytes of data:

Reply from 89.44.169.135: bytes=64 time=333ms TTL=49 (seq=0).
...
Reply from 89.44.169.135: bytes=64 time=333ms TTL=49 (seq=19).

Ping statistics for 89.44.169.135:
    Packets: Sent = 20, Received = 20, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 333ms, Maximum = 333ms, Average = 333ms


Pinging 31.216.148.10 with 64 bytes of data:

Reply from 31.216.148.10: bytes=64 time=416ms TTL=49 (seq=0).
...
Request timed out (seq=6).
Reply from 31.216.148.10: bytes=64 time=383ms TTL=49 (seq=7).
...
Request timed out (seq=13).
Reply from 31.216.148.10: bytes=64 time=350ms TTL=49 (seq=14).
...
Reply from 31.216.148.10: bytes=64 time=416ms TTL=49 (seq=19).

Ping statistics for 31.216.148.10:
    Packets: Sent = 20, Received = 18, Lost = 2 (10% loss),
Approximate round trip times in milli-seconds:
    Minimum = 350ms, Maximum = 416ms, Average = 384ms


Thank U, I modified it myself. :)

**Closed** 2018-12-18 05:51 UTC
